---
version: '2'

services:

    zookeeper:
        image: kafka
        build:
            context: .
            dockerfile: ./Dockerfile-dev
        container_name: zookeeper
        command: ./bin/zookeeper-server-start.sh config/zookeeper.properties
        ports:
            - 2181:2181
        expose:
            - 2181

    kafka:
        image: kafka
        build:
            context: .
            dockerfile: ./Dockerfile-dev
        container_name: kafka
        command: ./bin/kafka-server-start.sh config/server.properties
        links:
            - zookeeper
        ports:
            - 9092:9092
        expose:
            - 9092
        depends_on:
            - zookeeper
